### ISSUE TITLE
The code sucks

### ISSUE THREAD

**Issue by BloomVPS** [ClumsyAdmin/ClumsyLoader#1]
Jk good job Clumsy!

**Comment by NotGeri** [comment]
Can confirm, happens on v1.0.0

**Comment by RebelMythik** [comment]
> Jk good Jon Clumsy!

We have an issue with the issue

**Comment by ClumsyAdmin** [comment]
NO LOGS!??!?!? I'M CLOSING THIS.

**Comment by FinlayHDev** [comment]
I have logs! 
https://bin.bloom.host/fijosisayo.nginx

**Comment by Amgelo563** [comment]
Please reopen, still experiencing it on latest version

**Comment by Amgelo563** [comment]
Attaching logs https://bin.bloom.host/urekupazaw.sql pls fix

**Comment by ClumsyAdmin** [comment]
I swear to god...
