### ISSUE TITLE
Total size isn't being reported correctly

### ISSUE THREAD

**Issue by Jarva** [ClumsyAdmin/ClumsyLoader#3]
`resp2.Size()/1048576` is always returning 0, and the progress isn't updating, giving no real indication of the amount downloaded

The API exposes the `bytes` fields on the same object you fetch the `uuid` from. This could be used to generate the progress percentage as the amount downloaded increases.

**Comment by ClumsyAdmin** [comment]
Hey! Thanks for the issue, since I made this software specifically for Bloom's Panel I did not implement that because we don't expose that field because we can't since our backups are generated in real time and the full size of the backup isn't known until backup completion.

**Comment by Jarva** [comment]
I was using the tool with Bloom's panel and querying Bloom's API, it does have a `bytes` field in the response.
